spring:
  profiles:
    active: alpha
---
server:
  servlet:
    context-path: /
  port: 80
spring:
  profiles: alpha
  datasource:
    url: jdbc:mysql://localhost/cinema?serverTimezone=GMT&allowPublicKeyRetrieval=true
    username: root
    password: sql7549785
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource